### ISSUE TITLE
Update to Dot Net Tracer 2.44

### ISSUE THREAD

**Issue by jwyza-pi** [DataDog/datadog-aas-linux#18]
This is still running on Dot Net Tracer 2.40 by default which does not have official support for .Net 8.  Can we get this bumped up to 2.44?

**Comment by purple4reina** [comment]
Hey @jwyza-pi thanks for bringing this to our attention. We can get a release out for you sometime next week. In the meantime, you can always specify the tracer version by setting the environment variable `DD_DOTNET_TRACER_VERSION=2.44.0`.

**Comment by jwyza-pi** [comment]
Thanks, I did find that and started using it.  Doesn't solve the original issue I was having, but I think I'll open up a support call as I don't think it's likely related to this specific wrapper.

**Comment by jwyza-pi** [comment]
One other thing.  I noticed that the datadog agent currently packaged is 7.43.  That's pretty out of date too (February 20th).

**Comment by purple4reina** [comment]
> One other thing. I noticed that the datadog agent currently packaged is 7.43. That's pretty out of date too (February 20th).

Very nice, I'll make sure that's included in the release.
